# Generated by Django 4.2.23 on 2025-10-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='media-faylar/default.png', upload_to=''),
        ),
    ]
