# Generated by Django 5.2.1 on 2025-10-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'verbose_name': 'Muallif', 'verbose_name_plural': 'Mualliflar'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'verbose_name': 'Kitob va Muallif', 'verbose_name_plural': 'Kitob-Muallif aloqalari'},
        ),
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-id'], 'verbose_name': 'Kitob Sharhi', 'verbose_name_plural': 'Kitob Sharhlari'},
        ),
        migrations.AlterUniqueTogether(
            name='bookauthor',
            unique_together={('book', 'author')},
        ),
    ]
